apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: pingpong-svc
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
