apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pingpong/manifests/deployment.yaml
- pingpong/manifests/service.yaml
- pingpong/manifests/psql.yaml
images:
- name: le36/ping-pong
  newName: le36/ping-pong
  newTag: 71ed623f068413ff9a9fc6f88c5ad151563e606d
