apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: ping-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
