apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-check
  namespace: project
spec:
  metrics:
    - name: cpu-usage
      interval: 30s
      count: 3
      successCondition: result < 1
      failureCondition: result >= 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1735-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[10m])))
