apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: postgres-stset
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgres
          image: postgres:16.6
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: tododb
            - name: POSTGRES_USER
              value: todouser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        namespace: project
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: project
  name: postgres-svc
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgresdb
