apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: ping-claim
      containers:
        - name: writer
          image: le36/hashgenerator:latest
          command: [ "npm", "run", "writer" ]
          volumeMounts:
            - name: shared-data
              mountPath: /data

        - name: reader
          image: le36/hashgenerator:latest
          command: [ "npm", "run", "reader" ]
          volumeMounts:
            - name: shared-data
              mountPath: /data
          ports:
            - containerPort: 3000
