name: Build and Publish Application

on:
  push:
    branches:
      - gitops

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |-
          docker build --tag "le36/ping-pong:${GITHUB_SHA}" ./pingpong
          docker push "le36/ping-pong:${GITHUB_SHA}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image in kustomization.yaml
        working-directory: .
        run: kustomize edit set image le36/ping-pong=le36/ping-pong:${GITHUB_SHA}

      - name: Commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}